CREATE TABLE Cats (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(30) NOT NULL,
  color VARCHAR(30) NOT NULL,
  breed VARCHAR(30) NOT NULL
);


CREATE TABLE Toys (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(30) NOT NULL,
  color VARCHAR(30) NOT NULL,
  price NUMERIC(4,2) NOT NULL
);

CREATE TABLE CatToys (
  id SERIAL PRIMARY KEY NOT NULL,
  catId INTEGER NOT NULL,
  toyId INTEGER NOT NULL,
  FOREIGN KEY (catId) REFERENCES Cats(id),
  FOREIGN KEY (toyId) REFERENCES Toys(id)
);
